---
title: "Final Project Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(rsconnect)

homeless_data <- read.csv("2019-2020-homeless-ip-and-ed-by-facility.csv")
age_clean <- read.csv("./processed data/demo/cleaned_age_demo.csv")
ethnicity_clean <- read.csv("./processed data/demo/cleaned_ethnicity_demo.csv")
gender_clean <- read.csv("./processed data/demo/cleaned_gender_demo.csv")
race_clean <- read.csv("./processed data/demo/cleaned_race_demo.csv")

```

Homeless People Receiving Hospital Healthcare Services in Hospitals
===================================== 

Column {data-height=350}
-----------------------------------------------------------------------

```{r}
DemoValue = homeless_data |> distinct(EncounterType) |> pull()

radioButtons(
  inputId = "DemoValue", 
  label = h3("Select the Hospital's Type of Encounters (for Bar Plot)"),
  choices = DemoValue,
  selected = "Inpatient Hospitalizations")

DemoValue2 = homeless_data |> distinct(Ownership) |> pull()

radioButtons(
  inputId = "DemoValue2", 
  label = h3("Select the Hospital's Type of Ownership (for Bar Plot)"),
  choices = DemoValue2,
  selected = "Government")

DemoValue3 = homeless_data |> distinct(Demographic) |> pull()

selectInput(
  inputId = "DemoValue3",
  label = h3("Select the type of Demographic Value for Homelessnes (for Pie Chart)"),
  choices = DemoValue3,
  selected = "Age")
```

Column {data-height=350}
-----------------------------------------------------------------------

### Pie Chart

```{r}
homeless_pie =
  homeless_data |>
  group_by(Demographic, DemographicValue) |>
  summarise(total_homelessness = sum(Encounters))

renderPlotly({
  homeless_pie |>
    filter(Demographic == input$DemoValue3) |>
    plot_ly(labels = ~DemographicValue, values = ~total_homelessness, type ="pie") |>
     layout(
       title = list(text = "Total Homelessness by Different Types of Demographic Parameters", font = list(size = 14)),
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)
         )
})
```


Column {data-height=350}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  homeless_data |>
    filter(!is.na(HospitalCounty),
           EncounterType == input$DemoValue,
           Ownership == input$DemoValue2) |>
    group_by(HospitalCounty) |>
    summarise(count = sum(Encounters)) |>
    top_n(10, count) |>
    mutate(
      HospitalCounty = fct_reorder(HospitalCounty,count)
      ) |>
    plot_ly(x = ~HospitalCounty, y = ~count, color = ~HospitalCounty, type = "bar") %>% 
    layout(
      title = "Top 10 Californian Counties By Encounters of Homelessness", 
      xaxis = list(title = "Counties"),
      yaxis = list(title = "Number of Homelessness")
      )
})
```

Homeless People by Age
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
min_year = 2017
max_year = 2023

sliderInput(
  inputId = "year",
  label = h4("Choose Year"),
  min = min_year, max = max_year, value = c(2018, 2019))

loc = age_clean |> distinct(location) |> pull() 

selectInput(
  inputId = "loc", 
  label = h3("Choose Location"), 
  choices = loc, selected = "California")
```

Column {data-height=650}
-----------------------------------------------------------------------

### Pie Chart

```{r}
age_pie = 
  age_clean |>
  group_by(location, age_group_public) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  age_pie |>
    filter(location == input$loc) |>
    plot_ly(labels = ~age_group_public, values = ~total_homelessness, type ="pie") |>
     layout(title = "Total Homelessness by Age across Locations",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

Column {data-height=350}
-----------------------------------------------------------------------

### Bar Plot

```{r}
age_bar = 
  age_clean |>
  group_by(calendar_year, age_group_public) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  age_bar |> 
    filter(calendar_year %in% input$year[1]:input$year[2]) |>
    plot_ly(x = ~age_group_public, y = ~total_homelessness, type = "bar") |>
    layout(
      title = "Total Homelessness by Age across Years")
})
```

Homeless People by Race
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
min_year = 2017
max_year = 2023

sliderInput(
  inputId = "year2",
  label = h4("Choose Year"),
  min = min_year, max = max_year, value = c(2018, 2019))

loc = race_clean |> distinct(location) |> pull() 

selectInput(
  inputId = "loc2", 
  label = h3("Choose Location"), 
  choices = loc, selected = "California")
```

Row{data-height=650}
-----------------------------------------------------------------------

### Pie Chart

```{r}
race_pie = 
  race_clean |>
  group_by(location, race) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  race_pie |>
    filter(location == input$loc2) |>
    plot_ly(labels = ~race, values = ~total_homelessness, type ="pie") |>
     layout(title = "Total Homelessness by Race across Locations",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

Row{data-height=350}
-----------------------------------------------------------------------

### Bar Plot

```{r}
race_box = 
  race_clean |>
  group_by(calendar_year,race) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  race_box |> 
    filter(calendar_year %in% input$year2[1]:input$year2[2]) |>
    plot_ly(x = ~race, y = ~total_homelessness, type = "bar") |>
    layout(
      title = "Total Homelessness by Race across Years")
})
```

Homeless People by Ethnicity
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
min_year = 2017
max_year = 2023

sliderInput(
  inputId = "year3",
  label = h4("Choose Year"),
  min = min_year, max = max_year, value = c(2018, 2019))

loc = ethnicity_clean |> distinct(location) |> pull() 

selectInput(
  inputId = "loc3", 
  label = h3("Choose Location"), 
  choices = loc, selected = "California")
```

Row{data-height=650}
-----------------------------------------------------------------------

### Pie Chart

```{r}
ethnicity_pie = 
  ethnicity_clean |>
  group_by(location, ethnicity) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  ethnicity_pie |>
    filter(location == input$loc3) |>
    plot_ly(labels = ~ethnicity, values = ~total_homelessness, type ="pie") |>
     layout(title = "Total Homelessness by Ethnicity across Locations",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

Row{data-height=350}
-----------------------------------------------------------------------

### Bar Plot

```{r}
ethnicity_box = 
  ethnicity_clean |>
  group_by(calendar_year,ethnicity) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  ethnicity_box |> 
    filter(calendar_year %in% input$year3[1]:input$year3[2]) |>
    plot_ly(x = ~ethnicity, y = ~total_homelessness, type = "bar") |>
    layout(
      title = "Total Homelessness by Ethnicity across Years")
})
```

Homeless People by Gender
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
min_year = 2017
max_year = 2023

sliderInput(
  inputId = "year4",
  label = h4("Select Year"),
  min = min_year, max = max_year, value = c(2018, 2019))

loc = gender_clean |> distinct(location) |> pull() 

selectInput(
  inputId = "loc4", 
  label = h3("Choose Location"), 
  choices = loc, selected = "California")
```

Row{data-height=650}
-----------------------------------------------------------------------

### Pie Chart

```{r}
gender_pie = 
  gender_clean |>
  group_by(location, gender) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  gender_pie |>
    filter(location == input$loc4) |>
    plot_ly(labels = ~gender, values = ~total_homelessness, type ="pie") |>
     layout(title = "Total Homelessness by Gender across Locations",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
})
```

Row{data-height=350}
-----------------------------------------------------------------------

### Bar Plot

```{r}
gender_box = 
  gender_clean |>
  group_by(calendar_year,gender) |>
  summarise(total_homelessness = sum(experiencing_homelessness))

renderPlotly({
  gender_box |> 
    filter(calendar_year %in% input$year4[1]:input$year4[2]) |>
    plot_ly(x = ~gender, y = ~total_homelessness, type = "bar") |>
    layout(
      title = "Total Homelessness by Gender across Years")
})
```
